services:
  - name: sistema-automatizacion
    type: web
    env: docker
    plan: free
    dockerfilePath: ApiSAT/Dockerfile
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: PORT
        value: 80

