services:
  - type: web
    name: SistemaAutomatizacionTesis-Backend
    env: docker
    plan: free
    rootDir: ApiSAT
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    ports:
      - "80:80"
      - "8080:8080"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: host
      - key: DB_PORT
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: password
      - key: QUEUE_CONNECTION
        value: redis
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_HOST
        fromService:
          name: SistemaAutomatizacionTesis-Redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: SistemaAutomatizacionTesis-Redis
          type: redis
          property: port

  - name: SistemaAutomatizacionTesis-Redis
    type: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0

databases:
  - name: SistemaAutomatizacionTesis-DB
    plan: free
