services:
  - type: web
    name: SistemaAutomatizacionTesis-Backend
    env: docker
    plan: free
    dockerfilePath: ./ApiSAT/Dockerfile
    buildCommand: ""
    startCommand: "cd ApiSAT && php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false # Render maneja esto como secreto
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: host
      - key: DB_PORT
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: databaseName
      - key: DB_USERNAME
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: password

databases:
  - name: SistemaAutomatizacionTesis-DB
    plan: free
