services:
  - name: sistema-automatizacion
    type: web
    env: docker
    plan: free
    dockerfilePath: ApiSAT/Dockerfile
    buildCommand: docker-compose build
    envVars:
      - key: PORT
        value: 80
      - key: USER
        value: jistoria
      - key: UID
        value: 1000
