services:
  - type: web
    name: SistemaAutomatizacionTesis-Backend
    env: docker
    plan: free
    dockerfilePath: ./ApiSAT/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:FI7IdFnIW4rMX4onyyrh61IQ8x8DBiY+QfMC23mdTCM=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false # Render generará este valor automáticamente
      - key: DB_PORT
        sync: false # Render generará este valor automáticamente
      - key: DB_DATABASE
        sync: false # Render generará este valor automáticamente
      - key: DB_USERNAME
        sync: false # Render generará este valor automáticamente
      - key: DB_PASSWORD
        sync: false # Render generará este valor automáticamente

databases:
  - name: SistemaAutomatizacionTesis-DB
    plan: free
