services:
  - type: web
    name: SistemaAutomatizacionTesis-Backend
    env: docker
    plan: free
    dockerfilePath: ./ApiSAT/Dockerfile
    buildCommand: ""
    startCommand: ""
    sourceDir: ./ApiSAT


databases:
  - name: SistemaAutomatizacionTesis-DB
    plan: free
