services:
  - type: web
    name: SistemaAutomatizacionTesis-Backend
    env: docker
    plan: free
    dockerfilePath: ./ApiSAT/Dockerfile
    buildCommand: ""
    startCommand: "cd ApiSAT"
    enVars:
      - key: "DATABASE_URL"
        fromDatabase:
          name: SistemaAutomatizacionTesis-DB
          property: connectionString


databases:
  - name: SistemaAutomatizacionTesis-DB
    plan: free
