version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./storage/logs:/var/www/storage/logs
      - ./bootstrap/cache:/var/www/bootstrap/cache
    ports:
      - "8000:80"
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:FI7IdFnIW4rMX4onyyrh61IQ8x8DBiY+QfMC23mdTCM=
      - QUEUE_CONNECTION=redis
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REVERB_APP_ID=322986
      - REVERB_APP_KEY=4c9e0v0wg5rd8kmj62sb
      - REVERB_APP_SECRET=s83vcw925vaq5td8hxx0
      - REVERB_HOST="localhost"
      - REVERB_PORT=8080
      - REVERB_SCHEME=http
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
