services:
  - name: sistema-automatizacion
    type: web
    env: docker
    plan: free
    dockerfilePath: ./docker-compose.yml
    buildCommand: docker-compose build
    startCommand: docker-compose up
